### ISSUE TITLE
invalid json in HA sensor discovery for Water_pressure

### ISSUE THREAD

**Issue by fuecy** [Arnold-n/P1P2MQTT#80]
Hi Arnold,

Something minor for Water_pressure. There is an invalid json in the HA sensor discovery. It looks like unit_of_meas is missing. "bar" is in the string, but the key is missing.

{"name":"M1_Water_pressure","stat_t":"P1P2/P/018/M/1/Water_pressure","uniq_id":"M1_Water_pressure_018",bar"ic":"mdi:water","dev":{"name":"P1P2-018","ids":["P1P2ID018"],"mf":"NPC","mdl":"P1P2MQTT_bridge","sw":"0.9.41"}}

**Comment by Arnold-n** [comment]
Hi @fuecy,

Thanks for noting this, this will be solved in 0.9.42.
