### ISSUE TITLE
P1P2-adapter - Where to buy

### ISSUE THREAD

**Issue by 111lisu** [Arnold-n/P1P2MQTT#91]
[`Where to buy?`](https://github.com/Arnold-n/P1P2Serial/raw/main/circuits/P1P2adapter_topside.png)

**Comment by knightphoenix** [comment]
This is written on the main page

"How can you build or buy one?

Buy new complete stand-alone P1P2-ESP-interface): I have a number of factory-assembled PCBs available (with ATmega328P and ESP12F, bus-powered, with enclosure, soldered, pre-programmed, optionally with ethernet, with an option for an external power supply, documented and tested; currently available is version 3, v1.2, which is similar to v1.1 shown above). Please let me know if you are interested: my e-mail address can be found on line 3 of P1P2Serial.cpp."
